default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: rails_user
  password: '1'
  host: localhost
  

development:
  <<: *default
  database: stack_development


test:
  <<: *default
  database: stack_test
